name: Integration Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

    branches:
      - main

jobs:
  run_test:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Restore Go cache
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            ${{ runner.os }}-go-
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.x'
      - name: Run make test
        run: |
          make test
